import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';

import { QueryProvider } from '@/0_app/query';
import { StoreProvider } from '@/0_app/redux';

import './globals.css';

const manropeSans = Manrope({
  variable: '--font-manrope-sans',
  subsets: ['latin', 'cyrillic'],
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QueryProvider>
      <StoreProvider>
        <html lang="ru">
          <body className={`${manropeSans.variable} antialiased`}>{children}</body>
        </html>
      </StoreProvider>
    </QueryProvider>
  );
}
