import clsx from 'clsx';
import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';

import { QueryProvider } from '@/0_app/query';
import { StoreProvider } from '@/0_app/redux';

import './globals.css';

const manropeSans = Manrope({
  variable: '--font-manrope-sans',
  subsets: ['latin', 'cyrillic'],
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={clsx(
          'overflow-x-hidden overflow-y-auto bg-background text-body text-black antialiased',
          manropeSans.variable
        )}
      >
        <QueryProvider>
          <StoreProvider>{children}</StoreProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
